compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
gpu_ids: all # GPUs you want to use (i.e. 0,1,2)
machine_rank: 0 # Machine accelerate launch is called on
main_process_ip: localhost # Master IP
main_process_port: 29500   # Master Port
main_training_function: main
mixed_precision: bf16
num_machines: 1 # Num of machines
num_processes: 1  # Num of processes, processes_per_node is set for each node using its (num_machines // num_processes)
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false