apiVersion: v1
kind: Service
metadata:
  name: llama-2-13b-chat
spec:
  selector:
    app: llama
    statefulset.kubernetes.io/pod-name: llama-2-13b-chat-0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llama-2-13b-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - llama
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: llama-container
          image: aimodelsregistry.azurecr.io/llama-2-13b-chat:latest
          command:
            - /bin/sh
            - -c
            - |
              NODE_RANK=$(echo $HOSTNAME | grep -o '[^-]*$')
              EXTERNAL_IP=$(kubectl get svc llama-2-13b-chat -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              cd /workspace/llama/llama-2 && torchrun --nnodes 2 --nproc_per_node 1 --node_rank $NODE_RANK --master_addr $EXTERNAL_IP --master_port 29500 web_example_chat_completion.py
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      tolerations:
        - effect: NoSchedule
          key: sku
          operator: Equal
          value: gpu
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      nodeSelector:
        pool: lama213bchat
