apiVersion: v1
kind: Service
metadata:
  name: llama-2-13b
spec:
  selector:
    app: llama
    statefulset.kubernetes.io/pod-name: llama-2-13b-0
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: torchrun
      protocol: TCP
      port: 29500
      targetPort: 29500
  type: LoadBalancer
  publishNotReadyAddresses: true
