apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llama-2-13b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: llama
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - llama
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: llama-container
          image: aimodelsregistry.azurecr.io/llama-2-13b:latest
          env:
          - name: MASTER_ADDR
            value: "change-me"  # Placeholder that will be replaced
          command:
            - /bin/sh
            - -c
            - |
              echo "MASTER_ADDR: $MASTER_ADDR"
              NODE_RANK=$(echo $HOSTNAME | grep -o '[^-]*$')
              cd /workspace/llama/llama-2 && torchrun --nnodes 2 --nproc_per_node 1 --node_rank $NODE_RANK --master-addr $MASTER_ADDR --master-port 29500 web_example_text_completion.py
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 600 # 10 Min
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      tolerations:
        - effect: NoSchedule
          key: sku
          operator: Equal
          value: gpu
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      nodeSelector:
        pool: llama213b
