apiVersion: v1
kind: Service
metadata:
  name: llama-2-7b
spec:
  selector:
    app: llama
    statefulset.kubernetes.io/pod-name: llama-2-7b-0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  publishNotReadyAddresses: true
