apiVersion: v1
kind: Service
metadata:
  name: falcon-40b
spec:
  selector:
    app: falcon
    statefulset.kubernetes.io/pod-name: falcon-40b-0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  publishNotReadyAddresses: true
