run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - structcheck
    - typecheck
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: true
