apiVersion: v1
kind: Pod
metadata:
  name: python-chroma-pod
spec:
  containers:
    - name: python-chroma
      image: python:3.10  # Use Python base image
      command: ["sh", "-c", "sleep infinity"]  # This command runs your Python script
      volumeMounts:
        - name: app-volume
          mountPath: /app
      workingDir: /app
  initContainers:
    - name: install-dependencies
      image: python:3.10  # Use Python base image
      command:
        - sh
        - -c
        - |
          pip install chromadb llama-index ipython
          pip install huggingface-hub
          mkdir -p /app
      volumeMounts:
        - name: app-volume
          mountPath: /app
      workingDir: /app
      # Add your application code into the pod
    # - name: copy-code
    #   image: busybox
    #   command: ['sh', '-c', 'cp -r /source/* /app']
    #   volumeMounts:
    #     - name: app-volume
    #       mountPath: /app
        # - name: code-volume
        #   mountPath: /source
  volumes:
    - name: app-volume
      emptyDir: {}
    # - name: code-volume
    #   hostPath:
    #     path: /Users/ishaansehgal/Documents/kaito-repo/presets/rag_service/vector_store  # Path where your main.py is stored on the host machine
