env:
  # Workspace Service URL
  # Specify the URL for the Workspace Service inference endpoint. Use the DNS name within the cluster for reliability.
  #
  # Examples:
  # Cluster IP: "http://<CLUSTER_IP>:80/chat"
  # DNS name: "http://<SERVICE_NAME>.<NAMESPACE>.svc.cluster.local:80/chat"
  # e.g., "http://workspace-falcon-7b.default.svc.cluster.local:80/chat"
  workspaceServiceURL: "<YOUR_SERVICE_URL>"

# Incase Users want to expose service using a different type
# service: 
#   type: LoadBalancer