# values.yaml for Chainlit Front-end

replicaCount: 1
image:
  repository: python
  pullPolicy: IfNotPresent
  tag: "3.12"
imagePullSecrets: []
podAnnotations: {}
serviceAccount:
  create: false
  name: ""
service:
  type: ClusterIP
  port: 8000
  # env:
  # Workspace Service URL
  # Specify the URL for the Workspace Service inference endpoint. Use the DNS name within the cluster for reliability.
  #
  # Examples:
  # Cluster IP: "http://<CLUSTER_IP>:80"
  # DNS name: "http://<SERVICE_NAME>.<NAMESPACE>.svc.cluster.local:80"
  # e.g., "http://workspace-falcon-7b.default.svc.cluster.local:80"
  #
  # workspaceServiceURL: "<YOUR_SERVICE_URL>"
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi
livenessProbe:
  tcpSocket:
    port: 8000
  failureThreshold: 12
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  tcpSocket:
    port: 8000
  failureThreshold: 12
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
env:
  runtime: "vllm" # "vllm" or "transformers"
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: false