# permissions for end users to edit workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kdm
    app.kubernetes.io/part-of: kdm
    app.kubernetes.io/managed-by: kustomize
  name: workspace-editor-role
rules:
  - apiGroups: ["kdm.io"]
    resources: ["workspaces"]
    verbs: ["create", "delete", "update", "patch","get","list","watch"]
  - apiGroups: ["kdm.io"]
    resources: ["workspaces/status"]
    verbs: ["create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "update", "patch"]
  - apiGroups: [ "" ]
    resources: [ "pods"]
    verbs: [ "create", "update", "patch" ]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["update", "patch", "get"]
  - apiGroups: [ "apps" ]
    resources: ["deployments" ]
    verbs: ["create", "delete","update", "patch"]
  - apiGroups: ["karpenter.sh"]
    resources: ["machines", "machines/status"]
    verbs: ["create", "delete", "update", "patch"]
