apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: workspace-editor-role-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kdm
    app.kubernetes.io/part-of: kdm
    app.kubernetes.io/managed-by: kustomize
  name: workspace-editor-role-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workspace-editor-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
