# permissions for end users to edit workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kdm
    app.kubernetes.io/part-of: kdm
    app.kubernetes.io/managed-by: kustomize
  name: workspace-editor-role
rules:
  - apiGroups:
      - kdm.io
    resources:
      - workspaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kdm.io
    resources:
      - workspaces/status
    verbs:
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
    verbs:
      - patch
      - update
      - get
  - apiGroups: ["karpenter.sh"]
    resources: ["machines", "machines/status"]
    verbs: ["create", "delete", "update", "patch"]
