# permissions for end users to view workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kaito
    app.kubernetes.io/part-of: kaito
    app.kubernetes.io/managed-by: kustomize
  name: workspace-viewer-role
rules:
- apiGroups: ["kaito.io"]
  resources: ["workspaces"]
  verbs: ["get","list","watch"]
- apiGroups: ["kaito.io"]
  resources: ["workspaces/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes", "namespaces"]
  verbs: ["get","list","watch"]
- apiGroups: [ "" ]
  resources: [ "pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get","list","watch"]
- apiGroups: ["karpenter.sh"]
  resources: ["machines", "machines/status"]
  verbs: ["get", "list", "watch"]

