# permissions for end users to view workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kdm
    app.kubernetes.io/part-of: kdm
    app.kubernetes.io/managed-by: kustomize
  name: workspace-viewer-role
rules:
- apiGroups:
  - kdm.io
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kdm.io
  resources:
  - workspaces/status
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - patch
    - update
    - watch

