FROM python:3.12-slim

ARG WEIGHTS_PATH
ARG MODEL_TYPE
ARG VERSION

# Set the working directory
WORKDIR /workspace

# Model weights
COPY ${WEIGHTS_PATH} /workspace/weights

COPY kaito/presets/workspace/dependencies/requirements.txt /workspace/requirements.txt

RUN pip install --no-cache-dir -r /workspace/requirements.txt

# 1. Huggingface transformers
COPY kaito/presets/workspace/inference/${MODEL_TYPE}/inference_api.py \
    kaito/presets/workspace/tuning/${MODEL_TYPE}/cli.py \
    kaito/presets/workspace/tuning/${MODEL_TYPE}/fine_tuning.py \
    kaito/presets/workspace/tuning/${MODEL_TYPE}/parser.py \
    kaito/presets/workspace/tuning/${MODEL_TYPE}/dataset.py \
    kaito/presets/workspace/tuning/${MODEL_TYPE}/metrics/metrics_server.py \
    /workspace/tfs/

# 2. vLLM
COPY kaito/presets/workspace/inference/vllm/inference_api.py /workspace/vllm/inference_api.py

# Chat template
ADD kaito/presets/workspace/inference/chat_templates /workspace/chat_templates

RUN echo $VERSION > /workspace/version.txt && \
    ln -s /workspace/weights /workspace/tfs/weights && \
    ln -s /workspace/weights /workspace/vllm/weights
