apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build-job-{{JOB_ID}}
spec:
  ttlSecondsAfterFinished: 600  # Job and its pods are deleted 10 min after job completion
  backoffLimit: 3  # Number of retries before marking the job as failed
  template:
    spec:
      containers:
      - name: docker
        image: docker:dind
        securityContext:
          privileged: true
        command: ["sh", "-c"]
        args:
          - |
            cd / # Ensure in Workdir
            # Start the Docker daemon in the background
            dockerd &
            # Wait for the Docker daemon to be ready
            while ! docker info > /dev/null 2>&1; do
              echo "Waiting for Docker daemon to start..."
              sleep 1
            done
            echo 'Docker daemon started'

            # Additional setup
            apk add --no-cache git
            git clone -b $PR_BRANCH https://github.com/Azure/kaito.git

            # Print Project Files
            echo 'Print Project Files'
            ls -R kaito/presets

            # Ensure the repo is fully cloned before proceeding
            if [ ! -d "kaito" ]; then
              echo "Git repository not cloned. Exiting."
              exit 1
            fi

            # Login to Docker registry
            echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin
            
            # Build and push the Docker image
            docker build -t $ACR_NAME.azurecr.io/{{IMAGE_NAME}}:$VERSION \
                         --build-arg WEIGHTS_PATH=/weights \
                         --build-arg VERSION={{VERSION}} \
                         --build-arg MODEL_TYPE={{MODEL_TYPE}} \
                         -f $DOCKERFILE_PATH /
            docker push $ACR_NAME.azurecr.io/{{IMAGE_NAME}}:$VERSION
        env:
          - name: ACR_USERNAME
            value: "{{ACR_USERNAME}}"
          - name: ACR_PASSWORD
            value: "{{ACR_PASSWORD}}"
          - name: ACR_NAME
            value: "{{ACR_NAME}}"
          - name: IMAGE_NAME
            value: "{{IMAGE_NAME}}"
          - name: PR_BRANCH
            value: "{{PR_BRANCH}}"
          - name: MODEL_TYPE
            value: "{{MODEL_TYPE}}"
          - name: DOCKERFILE_PATH
            value: "{{DOCKERFILE_PATH}}"
          - name: VERSION
            value: "{{VERSION}}"
        volumeMounts:
          - name: weight-volume
            mountPath: /weights
      volumes:
        - name: weight-volume
          hostPath:
            path: "{{HOST_WEIGHTS_PATH}}"
      restartPolicy: Never
