kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /datadrive
    containerPath: /datadrive
  - hostPath: /home
    containerPath: /home
  - hostPath: /datadrive/etcd
    containerPath: /var/lib/etcd