kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /mnt/storage
    containerPath: /mnt/storage
  - hostPath: /home
    containerPath: /home
  - hostPath: /mnt/storage/etcd
    containerPath: /var/lib/etcd