apiVersion: v1
entries:
  kaito:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-10-17T18:58:57.213765937Z"
    description: A Helm chart for Kubernetes
    digest: ae12ec265f9670cb81ab5ed512cbe23f18f014bcfd0b58743990e3eefc3faab6
    name: kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-10-17T19:07:43.759680591Z"
    description: A Helm chart for Kubernetes
    digest: 8e063c44c4e8e4f627f0f7b1fcf8badfd7953d9a351f042fd0e312dbeb1edbec
    name: kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito-0.0.1.tgz
    version: 0.0.1
generated: "2023-10-17T19:07:43.757454724Z"
