apiVersion: v1
entries:
  kaito:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-10-17T18:45:59.202954872Z"
    description: A Helm chart for Kubernetes
    digest: 72531200a71a96a6c1812624592ea4c649054d18529f8d0d50508e4d4cedb4f2
    name: kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-10-17T18:23:40.243669564Z"
    description: A Helm chart for Kubernetes
    digest: 91a984ef50dd29a6d1aa77065a6142c295ba070e294bea6346c8e9f3db07803f
    name: kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito-0.0.1.tgz
    version: 0.0.1
generated: "2023-10-17T18:45:59.20213196Z"
