apiVersion: v1
entries:
  gpu-provisioner:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-03-19T21:08:46.167945581Z"
    description: A Helm chart for gpu-provisioner
    digest: bfc333181628ea28a5705d703a57e5e7f8ef47bc6d53cf183e7e94696e2081b6
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/gpu-provisioner-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-03-04T19:13:04.285459152Z"
    description: A Helm chart for gpu-provisioner
    digest: 35e2a254b6f6609c3937a31cf865f711251aa397b1c0e8c1144b8317d2d77111
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/gpu-provisioner-0.1.0.tgz
    version: 0.1.0
  workspace:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-03-19T21:08:46.168402556Z"
    description: A Helm chart to install AI Toolchain Operator Workspace
    digest: 8e4b5309d671ca77db84ebc8e8138acd6411308c1912418de40658dc3a943745
    home: https://github.com/Azure/kaito
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    - email: ishaanforthewin@gmail.com
      name: ishaansehgal99
    name: workspace
    sources:
    - https://github.com/Azure/kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/workspace-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-03-04T19:13:04.286022224Z"
    description: A Helm chart to install AI Toolchain Operator Workspace
    digest: 7b808263ef6560d53b85d9a69423bf5b5dd0dc0816d24855a8a91e61ded2d27d
    home: https://github.com/Azure/kaito
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    - email: ishaanforthewin@gmail.com
      name: ishaansehgal99
    name: workspace
    sources:
    - https://github.com/Azure/kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/workspace-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-19T21:08:46.166978401Z"
