apiVersion: v1
entries:
  gpu-provisioner:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-11-15T18:22:49.714619545Z"
    description: A Helm chart for gpu-provisioner
    digest: e10662c5a51ebfdbb70fe511a1739766dbf530b0b4dcbf0076af36e7d011a49b
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/gpu-provisioner-0.1.0.tgz
    version: 0.1.0
  workspace:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-11-15T18:22:49.715360054Z"
    description: A Helm chart to install AI Toolchain Operator Workspace
    digest: 1cb3077c061c9de91a33f9e14e8aa17606eb38e51535e9997b453dc42283b93f
    home: https://github.com/Azure/kaito
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    - email: ishaanforthewin@gmail.com
      name: ishaansehgal99
    name: workspace
    sources:
    - https://github.com/Azure/kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/workspace-0.1.0.tgz
    version: 0.1.0
generated: "2023-11-15T18:22:49.713073427Z"
