apiVersion: v1
entries:
  gpu-provisioner:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-03-30T01:51:36.482332027Z"
    description: A Helm chart for gpu-provisioner
    digest: 9497f423045f15a6049aa3b4f574bd5e963a92e2b5a57237dbc4fae70b71f574
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/gpu-provisioner-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-03-04T19:13:04.285459152Z"
    description: A Helm chart for gpu-provisioner
    digest: 35e2a254b6f6609c3937a31cf865f711251aa397b1c0e8c1144b8317d2d77111
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/gpu-provisioner-0.1.0.tgz
    version: 0.1.0
  workspace:
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2024-03-30T01:51:36.482884319Z"
    description: A Helm chart to install AI Toolchain Operator Workspace
    digest: b7e8ebf11d3566a6a3bcbfb9964b4ff93b53e8e7d90c3d77f3bff6b725cb28e8
    home: https://github.com/Azure/kaito
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    - email: ishaanforthewin@gmail.com
      name: ishaansehgal99
    name: workspace
    sources:
    - https://github.com/Azure/kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/workspace-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-03-19T21:38:11.932572749Z"
    description: A Helm chart to install AI Toolchain Operator Workspace
    digest: e8a1351da2a36edc62badaa0ce1ea83bfc5ad1328b3c3e2822a12f74cb681118
    home: https://github.com/Azure/kaito
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    - email: ishaanforthewin@gmail.com
      name: ishaansehgal99
    name: workspace
    sources:
    - https://github.com/Azure/kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/workspace-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-03-04T19:13:04.286022224Z"
    description: A Helm chart to install AI Toolchain Operator Workspace
    digest: 7b808263ef6560d53b85d9a69423bf5b5dd0dc0816d24855a8a91e61ded2d27d
    home: https://github.com/Azure/kaito
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    - email: ishaanforthewin@gmail.com
      name: ishaansehgal99
    name: workspace
    sources:
    - https://github.com/Azure/kaito
    type: application
    urls:
    - https://Azure.github.io/kaito/charts/kaito/workspace-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-30T01:51:36.48133281Z"
