# Default values for kaito.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: helayoty/kaito
  pullPolicy: Always
  tag: 0.0.2

imagePullSecrets: []

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

webhook:
  port: 9443

presetRegistryName: aimodelsregistry.azurecr.io

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
