apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-provisioner-global-settings
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "gpu-provisioner.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- list .Values.settings "" | include "flattenSettings" | indent 2 }}
