apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gpu-provisioner.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "gpu-provisioner.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gpu-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: gpu-provisioner
    namespace:  {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gpu-provisioner.fullname" . }}-dns
  namespace: kube-system
  labels:
    {{- include "gpu-provisioner.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gpu-provisioner.fullname" . }}-dns
subjects:
  - kind: ServiceAccount
    name: gpu-provisioner
    namespace: {{ .Release.Namespace }}