apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-mistral-7b-instruct
  annotations:
    kaito.sh/enablelb: "False"
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      apps: mistral-7b-instruct
inference:
  preset:
    name: "mistral-7b-instruct"
