apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-llama-2-13b-chat
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      apps: llama-2-13b
inference:
  preset:
    name: "llama-2-13b-chat"
    accessMode: private
    presetOptions:
      image: <YOUR IMAGE URL>
