apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  annotations:
    kubernetes-kaito.sh/service-type: load-balancer
  name: workspace-llama-2-13b-chat
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      apps: llama-2-13b
inference:
  preset:
    name: "llama-2-13b-chat"
