apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-llama-2-70b-chat
resource:
  instanceType: "Standard_NC96ads_A100_v4"
  count: 2
  labelSelector:
    matchLabels:
      apps: llama-2-70b-chat
inference:
  preset:
    name: "llama-2-70b-chat"
    accessMode: private
    presetOptions:
      image: <YOUR IMAGE URL>
