apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  annotations:
    kubernetes-kaito.sh/service-type: load-balancer
  name: workspace-falcon-7b-instruct
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      apps: falcon-7b-instruct
inference:
  preset:
    name: "falcon-7b-instruct"
