apiVersion: kdm.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    kubernetes-kdm.io/service-type: load-balancer
  name: workspace-llama-70b-aks
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      apps: llama-70b
inference:
  preset:
    name: "llama2-70b"
