apiVersion: kdm.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    kubernetes-kdm.io/service-type: load-balancer
  name: workspace-llama-2-70b-chat
resource:
  instanceType: "Standard_NC96ads_A100_v4"
  count: 2
  labelSelector:
    matchLabels:
      apps: llama-2-70b
inference:
  preset:
    name: "llama-2-70b-chat"
