apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - cd /workspace/llama/llama-2-7b && torchrun web_example_text_completion.py
        name: llama-container
        image: ishaansehgal99/llama-2-7b:latest
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: sku
        operator: Equal
        value: gpu
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
---

apiVersion: v1
kind: Service
metadata:
  name: llama-service
spec:
  selector:
    app: llama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  