apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: falcon-7b-instruct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: falcon
    spec:
      containers:
        - name: falcon-container
          image: REPO_HERE.azurecr.io/falcon-7b-instruct:TAG_HERE
          command:
            - /bin/sh
            - -c
            - accelerate launch --config_file config.yaml --num_processes 1 --num_machines 1 --use_deepspeed --machine_rank 0 --gpu_ids all inference-api.py
          # resources:
          #   limits:
          #     nvidia.com/gpu: "1"
          #   requests:
          #     nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 600 # 10 Min
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      tolerations:
        - effect: NoSchedule
          key: sku
          operator: Equal
          value: gpu
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      nodeSelector:
        pool: on7binstruct
