# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-download-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-download-app
  template:
    metadata:
      labels:
        app: file-download-app
    spec:
      containers:
      - name: my-container
        image: smritidahal/file-download-app:latest
        ports:
        - containerPort: 80
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: file-download-service
spec:
  selector:
    app: file-download-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


