apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-phi-3-medium
resource:
  instanceType: "Standard_NC24ads_A100_v4"
  labelSelector:
    matchLabels:
      apps: phi-3
inference:
  preset:
    name: phi-3-medium-4k-instruct
    # Note: This configuration also works with the phi-3-medium-128k-instruct preset
