apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-tuning-falcon-7b
spec:
  resource:
    instanceType: "Standard_NC12s_v3"
    labelSelector:
      matchLabels:
        app: tuning-falcon-7b
  tuning:
    preset:
      name: falcon-7b
    method: lora
    config: tuning-config-map  # ConfigMap containing tuning arguments
    input:
      name: tuning-data
      hostPath: /path/to/your/input/data  # dataset on node
    output:
      hostPath: /path/to/store/output # Tuning Output
