## ref: https://github.com/Azure/karpenter/blob/988bc0685d50a20884b1161722c9aafe3de50239/.github/actions/upload-artifact/action.yml
name: UploadArtifacts
description: 'Uploads artifacts of a workflow as an archive of a directory so that another workflow that runs on workflow_run can download and use it'
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: /tmp/artifacts
