apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kdm.fullname" . }}-rolebinding
  labels:
   {{- include "kdm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kdm.fullname" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "kdm.fullname" . }}-sa
  namespace: {{ include "kdm.fullname" . }}
