apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kdm.fullname" . }}-rolebinding
  namespace: {{ include "kdm.fullname" . }}
  labels:
   {{- include "kdm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kdm.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kdm.fullname" . }}-sa
  namespace: {{ include "kdm.fullname" . }}
