apiVersion: v1
kind: Secret
metadata:
  name: webhook-cert
  namespace: {{ include "kdm.fullname" .}}
  labels:
    {{- include "kdm.labels" . | nindent 4 }}
data:
   server-key.pem: ""
   server-cert.pem: ""
   ca-cert.pem: ""
