apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdm.fullname" . }}
  namespace: {{ include "kdm.fullname" .}}
  labels:
    {{- include "kdm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080 
      targetPort: http-metrics
      protocol: TCP
    - name: https-webhook
      port: {{ .Values.webhook.port }}
      targetPort: https-webhook
      protocol: TCP
  selector:
    {{- include "kdm.selectorLabels" . | nindent 4 }}
