apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-volume
          mountPath: /home
        - name: llama-volume
          mountPath: /home/llama
      volumes:
      - name: host-volume
        hostPath:
          path: /actions-runner/_work/kdm/kdm
          type: Directory
      - name: llama-volume
        hostPath: 
          path: /llama
          type: Directory