apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-volume
          mountPath: /
        volumes:
        - name: host-volume
          hostPath:
            path: .
            type: Directory