# docker-job-template.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build-job-{{JOB_ID}}
spec:
  template:
    spec:
      containers:
      - name: docker
        image: docker:latest
        command: ["sh", "-c"]
        args: ["docker login -u $ACR_USERNAME -p $ACR_PASSWORD $ACR_NAME && \
                docker build -t $ACR_NAME.azurecr.io/{{IMAGE_NAME}}:$IMAGE_TAG . && \
                docker push $ACR_NAME.azurecr.io/{{IMAGE_NAME}}:$IMAGE_TAG"]
        env:
          - name: ACR_USERNAME
            value: "{{ACR_USERNAME}}"
          - name: ACR_PASSWORD
            value: "{{ACR_PASSWORD}}"
          - name: ACR_NAME
            value: "{{ACR_NAME}}"
          - name: IMAGE_TAG
            value: "{{IMAGE_TAG}}"
          - name: IMAGE_NAME
            value: "{{IMAGE_NAME}}"
      restartPolicy: Never
