name: markdown link

on:
  pull_request:
    paths:
      - "**.md"
      - "docs/**"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          # this will only show errors in the output
          use-quiet-mode: "yes"
          # this will show detailed HTTP status for checked links
          use-verbose-mode: "yes"
          config-file: ".github/markdown.links.config.json"
