name: markdown link

on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          # this will only show errors in the output
          use-quiet-mode: 'yes'
          # this will show detailed HTTP status for checked links
          use-verbose-mode: 'yes'
          config-file: '.github/markdown.links.config.json'
