name: markdown link

on:
  pull_request:
    paths:
      - "**.md"
      - "docs/**"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          # this will only show errors in the output
          use-quiet-mode: "yes"
          # this will show detailed HTTP status for checked links
          use-verbose-mode: "yes"
          config-file: ".github/markdown.links.config.json"
