name: Push image to ACR
on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  packages: read

env:
  GO_VERSION: '1.20'

jobs:
  publish:
    runs-on: ubuntu-20.04
    environment: publish-mcr
    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION  }}

      - name: Set Image Tag
        run: |
          echo "IMG_TAG=$(echo "${{ github.ref }}" | tr -d refs/tags/v)" >> $GITHUB_ENV
          echo "REPO_TAG=$(echo "${{ github.ref }}" | tr -d refs/tags/)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ env.REPO_TAG }}

      - name: 'Az CLI login'
        uses: azure/login@v1.5.0
        with:
          client-id: ${{ secrets.KAITO_MCR_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KAITO_MCR_SUBSCRIPTION_ID }}

      - name: 'Publish to ACR'
        id: Publish
        run: |
          az acr login -n ${{ secrets.KAITO_MCR_REGISTRY }}
          OUTPUT_TYPE=type=registry make docker-build-kaito
        env:
            VERSION: ${{ env.IMG_TAG }}
            REGISTRY: ${{ secrets.KAITO_MCR_REGISTRY }}/unlisted/aks/kaito
