name: Push image to ACR
on:
 workflow_dispatch:
   inputs:
     release_version:
       description: 'tag to be created for this image (i.e. vxx.xx.xx)'
       required: true

permissions:
  id-token: write
  contents: write
  packages: write

env:
  GO_VERSION: '1.20'
  IMAGE_NAME: 'workspace'

jobs:
  check-tag:
    runs-on:
      labels: [ "self-hosted", "1ES.Pool=1es-aks-kaito-agent-pool-ubuntu" ]
    environment: publish-mcr
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
       with:
         egress-policy: audit

     - name: validate version
       run: |
         echo "${{ github.event.inputs.release_version }}" | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+$'
     - id: get-tag
       name: Get tag
       run: echo "tag=$(echo ${{ github.event.inputs.release_version }})" >> $GITHUB_OUTPUT

     - name: Checkout
       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         fetch-depth: 0

     - name: Check for Tag
       run: |
          TAG="${{ steps.get-tag.outputs.tag }}"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "create_tag=$(echo 'false' )" >> $GITHUB_ENV
          else
            echo "create_tag=$(echo 'true' )" >> $GITHUB_ENV
          fi
     - name: 'Create tag'
       if:  ${{ env.create_tag == 'true' }}
       uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
       with:
         script: |
           github.rest.git.createRef({
             owner: context.repo.owner,
             repo: context.repo.repo,
             ref: 'refs/tags/${{ steps.get-tag.outputs.tag }}',
             sha: context.sha
           })

  publish:
    runs-on:
      labels: [ "self-hosted", "1ES.Pool=1es-aks-kaito-agent-pool-ubuntu" ]
    environment: publish-mcr
    needs:
      - check-tag
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - id: get-tag
        name: Get tag
        run: echo "IMG_TAG=$(echo ${{ needs.check-tag.outputs.tag }} | tr -d v)" >> $GITHUB_ENV

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION  }}
 
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ needs.check-tag.outputs.tag }}

      - name: 'Build Image'
        run: |
          OUTPUT_TYPE=type=docker ARCH=arm64 make docker-build-kaito
        env:
          VERSION: ${{ env.IMG_TAG }}
          REGISTRY: ${{ secrets.KAITO_MCR_REGISTRY }}/public/aks/kaito

      - name: Scan ${{ secrets.KAITO_MCR_REGISTRY }}/public/aks/kaito/${{ env.IMAGE_NAME }}:${{ env.IMG_TAG }}
        uses: aquasecurity/trivy-action@062f2592684a31eb3aa050cc61e7ca1451cecd3d # master
        with:
          image-ref: ${{ secrets.KAITO_MCR_REGISTRY }}/public/aks/kaito/${{ env.IMAGE_NAME }}:${{ env.IMG_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '5m0s'
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Dispatch tag to e2e test'
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-tag
          client-payload: '{"isRelease": true,"registry": "mcr.microsoft.com/aks/kaito","tag": "${{ needs.check-tag.outputs.tag }}"}'

      - name: Authenticate to ACR
        run: |
          az login --identity
          az acr login -n ${{ secrets.KAITO_MCR_REGISTRY }}

      - name: 'Publish to ACR'
        id: Publish
        run: |
          OUTPUT_TYPE=type=registry make docker-build-kaito
        env:
            VERSION: ${{ env.IMG_TAG }}
            REGISTRY: ${{ secrets.KAITO_MCR_REGISTRY }}/public/aks/kaito
