name: unit-tests

concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - release-**
    paths-ignore: ['docs/**', '**.md', '**.mdx', '**.png', '**.jpg']
  push:
    branches: [main]
    paths-ignore: ['docs/**', '**.md', '**.mdx', '**.png', '**.jpg']

permissions:
  contents: read
  packages: write
      
env:
  GO_VERSION: '1.20'

jobs:
  unit-tests:
    runs-on: ubuntu-latest 
    steps:
      - name:  Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION  }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run unit tests & Generate coverage
        run: |
          make unit-test

      - name: Upload Codecov report
        uses: codecov/codecov-action@v3
        with:
          ## Comma-separated list of files to upload
          files: ./coverage.txt
